DROP TABLE IF EXISTS Sales;
DROP TABLE IF EXISTS Oil;
DROP TABLE IF EXISTS view_0;
DROP TABLE IF EXISTS view_1;
DROP TABLE IF EXISTS view_2;
DROP TABLE IF EXISTS view_3;
DROP TABLE IF EXISTS view_4;
DROP TABLE IF EXISTS view_5;
